# cloudbuild-pack-inline.yaml
steps:
  - name: gcr.io/k8s-skaffold/pack
    entrypoint: bash
    secretEnv: ["CLERK_PK"]
    args:
      - -lc
      - |
        set -euo pipefail
        IMGURL="europe-west4-docker.pkg.dev/${PROJECT_ID}/app-images/juntereu:${BUILD_ID}"
        echo "Building $$IMGURL with pack…"
        pack build "$$IMGURL" \
          --builder gcr.io/buildpacks/builder:google-22 \
          --path . \
          --env "GOOGLE_ENTRYPOINT=npm start" \
          --env "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${CLERK_PK}"
        echo "Built $$IMGURL"

images:
  - "europe-west4-docker.pkg.dev/${PROJECT_ID}/app-images/juntereu:${BUILD_ID}"

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY/versions/latest
      env: CLERK_PK

