# steps:
# - id: 'fetch-secrets'
#   name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     export NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$$(gcloud secrets versions access latest --secret=CLERK_PK --format='ge' | tr -d '\n' | base64 --decode)

# steps:
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['ci']
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['run', 'build']
#   env:
#   - 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_Y2xlcmsuanVudGVyLmV1JA'
#   - 'CLERK_SECRET_KEY=sk_live_hEUWpfMYNnfUlApiG6l6b8uJLEatla9vrl3lyhvssW'
# #  - 'CLERK_SECRET_KEY=${_CLERK_SECRET_KEY}'
# #  - 'MONGODB_NL_URL=${_MONGODB_NL_URL}'
# #  - 'MONGODB_BE_URL=${_MONGODB_BE_URL}'       
# steps:
#   - name: gcr.io/k8s-skaffold/pack
#     args:
#       - build
#       - europe-west4-docker.pkg.dev/junter-uitzendbureau/cloud-run-source-deploy/juntereu/juntereu:$COMMIT_SHA
#       - --builder
#       - gcr.io/buildpacks/builder:latest
#       - --publish

# options:
#   machineType: E2_HIGHCPU_8
#   diskSizeGb: 200
# timeout: "1200s"
steps:
  - id: "fetch-secrets"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -euo pipefail
        # Secret Manager returns base64 in payload.data
        CLERK_PK_B64="$(gcloud secrets versions access latest --secret=CLERK_PK --format='get(payload.data)')"
        CLERK_SK_B64="$(gcloud secrets versions access latest --secret=CLERK_SK --format='get(payload.data)')"

        echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$(echo "$CLERK_PK_B64" | tr -d '\n' | base64 --decode)" > /workspace/build.env
        echo "CLERK_SECRET_KEY=$(echo "$CLERK_SK_B64" | tr -d '\n' | base64 --decode)" >> /workspace/build.env

  # If you want pack/buildpacks to do the build, you can remove these npm steps.
  # Keep them only if you truly need a prebuild for some other purpose.
  - id: "pack-build"
    name: "gcr.io/k8s-skaffold/pack"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -euo pipefail
        source /workspace/build.env

        pack build europe-west4-docker.pkg.dev/junter-uitzendbureau/cloud-run-source-deploy/juntereu/juntereu:$COMMIT_SHA \
          --builder gcr.io/buildpacks/builder:latest \
          --publish \
          --env NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_live_Y2xlcmsuanVudGVyLmV1JA" \
          --env CLERK_SECRET_KEY="sk_live_hEUWpfMYNnfUlApiG6l6b8uJLEatla9vrl3lyhvssW"

options:
  machineType: "E2_HIGHCPU_8"
  diskSizeGb: 200
  logging: NONE

timeout: "1200s"
