steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  env:
  - 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_Y2xlcmsuanVudGVyLmV1JA'
  - 'CLERK_SECRET_KEY=sk_live_hEUWpfMYNnfUlApiG6l6b8uJLEatla9vrl3lyhvssW'
  - 'MONGODB_NL_URL=mongodb+srv://akwasivdsm:Drve33REtwzIqqXo@thejunter.83qsl.mongodb.net/Nederland?retryWrites=true&w=majority&appName=thejunter'
  - 'DB_NAME=juntereu'       