[[build.env]]
    name = "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
    value = "pk_live_Y2xlcmsuanVudGVyLmV1JA" # Replace with your actual Clerk key if hardcoding

[[build.env]]
    name = "NPM_CONFIG_PRODUCTION"
    value = "false" # Example: to ensure dev dependencies are installed if needed during build

[[build.env]]
    name = "GOOGLE_ENTRYPOINT"
    value = "node server.js" # Example for Node.js, customizing the entry point
